version: "2.1"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=s3
      - LAMBDA_EXECUTOR=local
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  app:
    build: .
    volumes:
      - .:/app
      - nodemodules:/src/node_modules
    restart: on-failure
    ports:
      - 3001:3000
    links:
      - localstack
    depends_on:
      - localstack
    environment:
      LOCALSTACK_HOST: localstack
      S3_PORT: 4566

volumes:
  nodemodules: {}
